# Check this file before committing a new version:
# http://lint.travis-ci.org/

language: python
sudo: false
dist: trusty

python:
  - 2.7
  - 3.5
  - 3.6

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V

# command to install dependencies
install:
  - pip install -r pip-requirements.txt
  - python setup.py install


# command to run tests
script:
  - ./run-tests.sh
